import ImagePath from '../styles/images'

let backgrounds = {
  'Age of Empires 2'          :ImagePath('age_of_empires_2.jpg'),
  'Age of Mythology'          :ImagePath('age_of_mythology.jpg'),
  "Baldur's Gate"             :ImagePath('baldurs_gate.jpg'),
  'Battlefield 4'             :ImagePath('battlefield_4.jpg'),
  'Civilization V'            :ImagePath('civilization_v.jpg'),
  'Crusader Kings 2'          :ImagePath('crusader_kings_2.jpg'),
  'Dark Souls'                :ImagePath('dark_souls.jpg'),
  'Dungeons of Dredmor'       :ImagePath('dungeons_of_dredmor.jpg'),
  'Dwarf Fortress'            :ImagePath('dwarf_fortress.png'),
  'Endless Legend'            :ImagePath('endless_legend.jpg'),
  'Europa Universalis IV'     :ImagePath('europa_universalis_iv.jpg'),
  'Expeditions: Conquistador' :ImagePath('expeditions_conquistador.jpg'),
  'Fallout 3'                 :ImagePath('fallout3.jpg'),
  'Fallout: New Vegas'        :ImagePath('newvegas.jpg'),
  'FTL: Faster Than Light'    :ImagePath('ftl.png'),
  'GTA V: Online'             :ImagePath('gtavonline.jpg'),
  'Kerbal Space Program'      :ImagePath('ksp.jpg'),
  'Mass Effect'               :ImagePath('masseffect1.jpg'),
  'Mass Effect 2'             :ImagePath('masseffect2.jpg'),
  'Mass Effect 3'             :ImagePath('masseffect3.jpg'),
  'Minecraft'                 :ImagePath('minecraft.png'),
  'Mount and Blade'           :ImagePath('mountain_glade.jpg'),
  'Orcs Must Die'             :ImagePath('omd1.jpg'),
  'Orcs Must Die 2'           :ImagePath('omd2.jpg'),
  'Pillars of Eternity'       :ImagePath('pillars_of_eternity.jpg'),
  'Pokemon'                   :ImagePath('pokemon.jpg'),
  'Skyrim'                    :ImagePath('skyrim.jpg'),
  "Tales of Maj'Eyal"         :ImagePath('tome.jpg'),
  'Terraria'                  :ImagePath('terraria.jpg'),
  'Team Fortress 2'           :ImagePath('tf2.jpg'),
  'The Sims 3'                :ImagePath('sims3.jpg'),
  'The Sims 4'                :ImagePath('sims4.jpg'),
  'The Witcher'               :ImagePath('witcher.jpg'),
  'The Witcher 2'             :ImagePath('witcher2.jpg'),
  'X-Com: Enemy Unknown'      :ImagePath('xcom.jpg'),
  'X-Rebirth'                 :ImagePath('x_rebirth.png'),
}

export default backgrounds