import ImagePath from '../styles/images'

let backgrounds = {
  'Age of Empires 2':          ImagePath('backgrounds/age_of_empires_2.jpg'),
  'Age of Mythology':          ImagePath('backgrounds/age_of_mythology.jpg'),
  "Baldur's Gate":             ImagePath('backgrounds/baldurs_gate.jpg'),
  'Battlefield 4':             ImagePath('backgrounds/battlefield_4.jpg'),
  'Civilization V':            ImagePath('backgrounds/civilization_v.jpg'),
  'Crusader Kings 2':          ImagePath('backgrounds/crusader_kings_2.jpg'),
  'Dark Souls':                ImagePath('backgrounds/dark_souls.jpg'),
  'Dungeons of Dredmor':       ImagePath('backgrounds/dungeons_of_dredmor.jpg'),
  'Dwarf Fortress':            ImagePath('backgrounds/dwarf_fortress.png'),
  'Endless Legend':            ImagePath('backgrounds/endless_legend.jpg'),
  'Europa Universalis IV':     ImagePath('backgrounds/europa_universalis_iv.jpg'),
  'Expeditions: Conquistador': ImagePath('backgrounds/expeditions_conquistador.jpg'),
  'Fallout 3':                 ImagePath('backgrounds/fallout3.jpg'),
  'Fallout: New Vegas':        ImagePath('backgrounds/newvegas.jpg'),
  'FTL: Faster Than Light':    ImagePath('backgrounds/ftl.png'),
  'GTA V: Online':             ImagePath('backgrounds/gtavonline.jpg'),
  'Kerbal Space Program':      ImagePath('backgrounds/ksp.jpg'),
  'Mass Effect':               ImagePath('backgrounds/masseffect1.jpg'),
  'Mass Effect 2':             ImagePath('backgrounds/masseffect2.jpg'),
  'Mass Effect 3':             ImagePath('backgrounds/masseffect3.jpg'),
  'Minecraft':                 ImagePath('backgrounds/minecraft.png'),
  'Mount and Blade':           ImagePath('backgrounds/mountain_glade.jpg'),
  'Rimworld':                  ImagePath('backgrounds/rimworld.jpg'),
  'Orcs Must Die':             ImagePath('backgrounds/omd1.jpg'),
  'Orcs Must Die 2':           ImagePath('backgrounds/omd2.jpg'),
  'Pillars of Eternity':       ImagePath('backgrounds/pillars_of_eternity.jpg'),
  'Pokemon':                   ImagePath('backgrounds/pokemon.jpg'),
  'Skyrim':                    ImagePath('backgrounds/skyrim.jpg'),
  "Tales of Maj'Eyal":         ImagePath('backgrounds/tome.jpg'),
  'Terraria':                  ImagePath('backgrounds/terraria.jpg'),
  'Team Fortress 2':           ImagePath('backgrounds/tf2.jpg'),
  'The Sims 3':                ImagePath('backgrounds/sims3.jpg'),
  'The Sims 4':                ImagePath('backgrounds/sims4.jpg'),
  'The Witcher':               ImagePath('backgrounds/witcher.jpg'),
  'The Witcher 2':             ImagePath('backgrounds/witcher2.jpg'),
  'X-Com: Enemy Unknown':      ImagePath('backgrounds/xcom.jpg'),
  'X-Rebirth':                 ImagePath('backgrounds/x_rebirth.png'),
}

export default backgrounds
